name: Daily Reminder
on:
  schedule:
    - cron: "0 8 * * *" # Runs at 8:00 AM UTC daily
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Run reminder
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
        run: |
          go run main.go
